apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: online-boutique
resources:
  - ../../source/microservices-demo/kustomize/base
  - namespace.yaml
  - observability.yaml
patches:
  - target:
      kind: Service
      name: frontend-external
    patch: |-
      - op: replace
        path: /spec/type
        value: NodePort
  - target:
      kind: Deployment
      name: checkoutservice|currencyservice|emailservice|frontend|paymentservice|productcatalogservice|recommendationservice
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: COLLECTOR_SERVICE_ADDR
          value: opentelemetrycollector:4317
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: ENABLE_TRACING
          value: "1"
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: DISABLE_PROFILER
          value: "1"
      - op: add
        path: /spec/template/metadata/labels/experiment.run-id
        value: "ob-cpu-high-003"
      - op: add
        path: /spec/template/metadata/annotations
        value:
          experiment.run-id: "ob-cpu-high-003"
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: EXPERIMENT_RUN_ID
          value: "ob-cpu-high-003"
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: OTEL_SERVICE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['app']
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: OTEL_TRACES_SAMPLER
          value: "parentbased_traceidratio"
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: OTEL_TRACES_SAMPLER_ARG
          value: "1.0"
  - target:
      kind: Deployment
      name: loadgenerator
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: WORKLOAD_PROFILE_ID
          value: "ob-default-10u-1r-v1"
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: WORKLOAD_RANDOM_SEED
          value: "1"
      - op: add
        path: /spec/template/spec/containers/0/command
        value:
          - python
          - -c
      - op: add
        path: /spec/template/spec/containers/0/args
        value:
          - |
            import os
            import random
            import sys
            from faker import Faker

            seed = int(os.environ["WORKLOAD_RANDOM_SEED"])
            random.seed(seed)
            Faker.seed(seed)

            from locust.main import main
            main()
          - --host=http://$(FRONTEND_ADDR)
          - --headless
          - -u
          - $(USERS)
          - -r
          - $(RATE)
  - target:
        kind: Deployment
        name: emailservice
    patch: |-
        - op: add
          path: /spec/template/spec/containers/0/startupProbe
          value:
            grpc:
              port: 8080
            periodSeconds: 2
            timeoutSeconds: 2
            failureThreshold: 30
