[CmdletBinding(SupportsShouldProcess=$true,ConfirmImpact='Low')]
param([Parameter(Mandatory)][string]$DiagnosticId,[Parameter(Mandatory)][string]$RuntimeStateRoot,[Parameter(Mandatory)][string]$OnlineBoutiqueSourceRoot,[Parameter(Mandatory)][string]$PythonPath,[string]$Profile='p0-online-boutique',[switch]$ExecutionApproved)
$ErrorActionPreference='Stop';Set-StrictMode -Version Latest
. (Join-Path $PSScriptRoot 'env.ps1');. (Join-Path $PSScriptRoot 'phase-duration.ps1');. (Join-Path $PSScriptRoot 'host-event-recordid.ps1');. (Join-Path $PSScriptRoot 'host-network-context.ps1');. (Join-Path $PSScriptRoot 'kubernetes-optional-property.ps1')
$repo=(Resolve-Path(Join-Path $PSScriptRoot '..\..')).Path;$root=Join-Path $repo "p0-env\artifacts\P1-HOST-NETWORK-PORTABILITY-001\$DiagnosticId";$namespace='online-boutique';$closedDiagnosticId='ob-host-network-portability-wifi-001';$e2eRunId='ob-host-network-portability-wifi-002-e2e';$expectedSourceRevision='5b3a712ab85ccb8f6f7cd5b720d36ba9a8d041eb'
function NowUtc{[datetimeoffset]::UtcNow.ToString('yyyy-MM-ddTHH:mm:ss.fffffffZ')}
function WriteJson([string]$Path,$Value){New-Item -ItemType Directory -Path(Split-Path -Parent $Path)-Force|Out-Null;[IO.File]::WriteAllText($Path,($Value|ConvertTo-Json -Depth 80),[Text.UTF8Encoding]::new($false))}
function GetCleanBootPreflight{
 $boot=[datetimeoffset](Get-CimInstance Win32_OperatingSystem -ErrorAction Stop).LastBootUpTime;$events=[ordered]@{whea_event_17=@(Get-WinEvent -FilterHashtable @{LogName='System';ProviderName='Microsoft-Windows-WHEA-Logger';Id=17;StartTime=$boot.LocalDateTime}-ErrorAction SilentlyContinue).Count;kernel_power_41=@(Get-WinEvent -FilterHashtable @{LogName='System';ProviderName='Microsoft-Windows-Kernel-Power';Id=41;StartTime=$boot.LocalDateTime}-ErrorAction SilentlyContinue).Count;bugcheck=@(Get-WinEvent -FilterHashtable @{LogName='System';ProviderName='Microsoft-Windows-WER-SystemErrorReporting';Id=1001;StartTime=$boot.LocalDateTime}-ErrorAction SilentlyContinue).Count};if(($events.whea_event_17+$events.kernel_power_41+$events.bugcheck)-ne0){throw 'clean_boot_host_event_preflight_failed'}
 $free=[int64](Get-PSDrive -Name C -ErrorAction Stop).Free;if($free-lt15GB){throw 'host_free_space_below_15_gib'};$docker=@(& docker info --format '{{json .ServerVersion}}' 2>&1);if($LASTEXITCODE){throw 'docker_engine_not_ready'};$statusRaw=@(& minikube status --profile $Profile --output=json 2>&1);$statusExit=$LASTEXITCODE;try{$status=($statusRaw-join"`n")|ConvertFrom-Json -ErrorAction Stop}catch{throw 'existing_profile_status_unreadable'};if($statusExit-notin@(0,7)-or$status.Host-ne'Stopped'-or$status.Kubelet-ne'Stopped'-or$status.APIServer-ne'Stopped'){throw 'existing_profile_not_stopped'}
 [ordered]@{schema_version=1;observed_utc=NowUtc;boot_utc=$boot.ToUniversalTime().ToString('yyyy-MM-ddTHH:mm:ss.fffffffZ');events_since_boot=$events;free_space_bytes=$free;free_space_gate_bytes=[int64](15GB);docker_ready=$true;profile_status_native_exit_code=$statusExit;profile_status=[ordered]@{host=$status.Host;kubelet=$status.Kubelet;api_server=$status.APIServer};passed=$true}
}
function GetLoadgeneratorUid{$raw=@(& minikube kubectl --profile $Profile -- -n $namespace get pods -l app=loadgenerator -o json 2>&1);if($LASTEXITCODE){throw 'loadgenerator_snapshot_failed'};$pods=@((($raw-join"`n")|ConvertFrom-Json).items|Where-Object{$null-eq(Get-KubernetesOptionalProperty $_.metadata 'deletionTimestamp')});if($pods.Count-ne1){throw 'loadgenerator_count_invalid'};[string]$pods[0].metadata.uid}
function RestartLoadgenerator{& minikube kubectl --profile $Profile -- -n $namespace rollout restart deployment/loadgenerator|Out-Null;if($LASTEXITCODE){throw 'loadgenerator_restart_failed'};& minikube kubectl --profile $Profile -- -n $namespace rollout status deployment/loadgenerator --timeout=10m|Out-Null;if($LASTEXITCODE){throw 'loadgenerator_rollout_failed'}}
function NewBundle([string]$Source){$temp=Join-Path([IO.Path]::GetTempPath())('wifi-portability-'+[guid]::NewGuid().ToString('N'));New-Item -ItemType Directory -Path $temp -WhatIf:$false -Confirm:$false|Out-Null;Copy-Item -LiteralPath(Join-Path $Source 'kustomize\base')-Destination(Join-Path $temp 'upstream-base')-Recurse -WhatIf:$false -Confirm:$false;foreach($name in @('namespace.yaml','observability.yaml')){Copy-Item -LiteralPath(Join-Path $repo "p0-env\config\online-boutique\$name")-Destination(Join-Path $temp $name)-WhatIf:$false -Confirm:$false};$k=Get-Content -LiteralPath(Join-Path $repo 'p0-env\config\online-boutique\kustomization.yaml')-Raw;$k=$k.Replace('../../source/microservices-demo/kustomize/base','upstream-base').Replace('ob-netdelay-500m-normal-10u-004',$e2eRunId);[IO.File]::WriteAllText((Join-Path $temp 'kustomization.yaml'),$k,[Text.UTF8Encoding]::new($false));$o=Get-Content -LiteralPath(Join-Path $temp 'observability.yaml')-Raw;$o=$o.Replace('ob-netdelay-500m-normal-10u-004',$e2eRunId);[IO.File]::WriteAllText((Join-Path $temp 'observability.yaml'),$o,[Text.UTF8Encoding]::new($false));$temp}
function CaptureWindow([string]$Name,[int]$Seconds){$networkBefore=Get-HostNetworkContext wifi;$hostBefore=New-HostEventRecordIdBoundary;$uid=GetLoadgeneratorUid;$start=NowUtc;$end=Wait-UntilMinimumUtcDuration -StartUtc $start -MinimumSeconds $Seconds;$hostAfter=Measure-HostEventsAfterRecordIdBoundary $hostBefore;$networkAfter=Get-HostNetworkContext wifi;[void](Assert-HostNetworkContextStable $networkBefore $networkAfter);$value=[ordered]@{name=$Name;start_utc=$start;end_utc=$end;duration_seconds=([datetimeoffset]::Parse($end)-[datetimeoffset]::Parse($start)).TotalSeconds;loadgenerator_uid=$uid;network_before=$networkBefore;network_after=$networkAfter;network_stable=$true;host_events=$hostAfter};WriteJson(Join-Path $root "$Name.json")$value;if(-not$hostAfter.passed){throw "host_event_gate_failed:$Name"};$value}
function CaptureE2EWindow{
 $networkBefore=Get-HostNetworkContext wifi;$hostBefore=New-HostEventRecordIdBoundary;$uid=GetLoadgeneratorUid;$start=NowUtc;$end=Wait-UntilMinimumUtcDuration -StartUtc $start -MinimumSeconds 600
 $previous=$ErrorActionPreference;$ErrorActionPreference='Continue';try{$close=@(& powershell -NoProfile -ExecutionPolicy Bypass -File(Join-Path $PSScriptRoot 'close-run.ps1')-RunId $e2eRunId -StartUtc $start -EndUtc $end -TraceLimitPerService 5000 -TraceQueryChunkSeconds 300 2>&1);$closeExit=$LASTEXITCODE}finally{$ErrorActionPreference=$previous};[IO.File]::WriteAllLines((Join-Path $root 'e2e-close-output.txt'),@($close|ForEach-Object{[string]$_}),[Text.UTF8Encoding]::new($false))
 $hostAfter=Measure-HostEventsAfterRecordIdBoundary $hostBefore;$networkAfter=Get-HostNetworkContext wifi;[void](Assert-HostNetworkContextStable $networkBefore $networkAfter);$value=[ordered]@{name='e2e-window';start_utc=$start;end_utc=$end;duration_seconds=([datetimeoffset]::Parse($end)-[datetimeoffset]::Parse($start)).TotalSeconds;loadgenerator_uid=$uid;network_before=$networkBefore;network_after=$networkAfter;network_stable=$true;host_events=$hostAfter;application_telemetry_closure_passed=($closeExit-eq0-and($close-join"`n").Contains('close_run=passed'))};WriteJson(Join-Path $root 'e2e-window.json')$value;if(-not$hostAfter.passed){throw 'host_event_gate_failed:e2e-window'};if(-not$value.application_telemetry_closure_passed){throw 'e2e_close_failed'};$value
}
if(-not$ExecutionApproved){throw 'explicit_wifi_portability_runtime_approval_required'};if($DiagnosticId-eq$closedDiagnosticId){throw 'closed_diagnostic_id'};if($DiagnosticId-ne'ob-host-network-portability-wifi-002'){throw 'unexpected_diagnostic_id'};if($Profile-ne'p0-online-boutique'){throw 'unexpected_profile'};if(@(& git -C $repo status --porcelain).Count){throw 'working_tree_not_clean'};if(Test-Path -LiteralPath $root){throw 'immutable_diagnostic_output_exists'};if(-not(Test-Path -LiteralPath $PythonPath -PathType Leaf)){throw 'python_runtime_missing'}
$runtimeState=(Resolve-Path -LiteralPath $RuntimeStateRoot -ErrorAction Stop).Path;$source=(Resolve-Path -LiteralPath $OnlineBoutiqueSourceRoot -ErrorAction Stop).Path;$sourceRevision=(@(& git -C $source rev-parse HEAD 2>&1)-join'').Trim();if($LASTEXITCODE-or$sourceRevision-ne$expectedSourceRevision){throw 'online_boutique_source_revision_mismatch'};$env:MINIKUBE_HOME=$runtimeState;$env:P0_PYTHON_PATH=$PythonPath;$initialNetwork=Get-HostNetworkContext wifi;$cleanBootPreflight=GetCleanBootPreflight
if(-not$PSCmdlet.ShouldProcess($DiagnosticId,'run no-fault Wi-Fi host-network portability diagnostic')){return}
New-Item -ItemType Directory -Path $root|Out-Null;$bundle=$null;$stopped=$false;$failure=$null;$globalHostBefore=New-HostEventRecordIdBoundary
WriteJson(Join-Path $root 'diagnostic-manifest.json')([ordered]@{schema_version=1;gate_id='P1-HOST-NETWORK-PORTABILITY-001';diagnostic_id=$DiagnosticId;code_revision=(& git -C $repo rev-parse HEAD).Trim();preregistration_decision='D-107';transport='wifi';adapter_name=$initialNetwork.adapter_name;interface_description=$initialNetwork.interface_description;driver_version=$initialNetwork.driver_version;active_load_window_seconds=@(1800,1800);e2e_window_seconds=600;scientific_fault_started=$false;dataset_inclusion=$false;d067_inclusion=$false;privacy_contract='ssid_bssid_mac_ip_gateway_omitted'})
WriteJson(Join-Path $root 'clean-boot-preflight.json')$cleanBootPreflight
WriteJson(Join-Path $root 'global-host-before.json')$globalHostBefore
try{$bundle=NewBundle $source;& minikube start --profile $Profile --driver=docker --kubernetes-version=v1.34.0 --cpus=4 --memory=6144mb --disk-size=32g --container-runtime=containerd|Out-Null;if($LASTEXITCODE){throw 'minikube_start_failed'};& minikube kubectl --profile $Profile -- apply -k $bundle|Out-Null;if($LASTEXITCODE){throw 'base_apply_failed'};& minikube kubectl --profile $Profile -- -n $namespace wait --for=condition=Available deployment --all --timeout=15m|Out-Null;if($LASTEXITCODE){throw 'deployment_availability_failed'}
 $w1=CaptureWindow 'active-load-window-1' 1800;RestartLoadgenerator;$w2=CaptureWindow 'active-load-window-2' 1800;RestartLoadgenerator;$w3=CaptureE2EWindow
 & minikube stop --profile $Profile|Out-Null;if($LASTEXITCODE){throw 'minikube_stop_failed'};$stopped=$true;$previous=$ErrorActionPreference;$ErrorActionPreference='Continue';try{$offline=@(& powershell -NoProfile -ExecutionPolicy Bypass -File(Join-Path $PSScriptRoot 'verify-finalized-run.ps1')-ReceiptPath(Join-Path $repo "p0-env\artifacts\finalized\$e2eRunId") 2>&1);$offlineExit=$LASTEXITCODE}finally{$ErrorActionPreference=$previous};[IO.File]::WriteAllLines((Join-Path $root 'offline-receipt-verification.txt'),@($offline|ForEach-Object{[string]$_}),[Text.UTF8Encoding]::new($false));if($offlineExit-ne0-or-not(($offline-join"`n").Contains('finalized_run_verification=passed'))){throw 'offline_receipt_verification_failed'};$globalHostAfter=Measure-HostEventsAfterRecordIdBoundary $globalHostBefore;WriteJson(Join-Path $root 'global-host-after.json')$globalHostAfter;if(-not$globalHostAfter.passed){throw 'global_host_event_gate_failed'};WriteJson(Join-Path $root 'assessment.json')([ordered]@{schema_version=1;diagnostic_id=$DiagnosticId;classification='wifi_host_portability_supported';passed=$true;transport='wifi';adapter_name=$initialNetwork.adapter_name;interface_description=$initialNetwork.interface_description;driver_version=$initialNetwork.driver_version;active_load_windows_completed=2;active_load_window_seconds=@([int]$w1.duration_seconds,[int]$w2.duration_seconds);e2e_closure_seconds=[int]$w3.duration_seconds;application_telemetry_closure_passed=$true;offline_receipt_verification_passed=$true;host_event_windows=@($w1.host_events.counts,$w2.host_events.counts,$w3.host_events.counts);global_host_events=$globalHostAfter.counts;dataset_inclusion=$false;d067_inclusion=$false})
}catch{$failure=$_.Exception.Message;WriteJson(Join-Path $root 'run-error.json')([ordered]@{failed_utc=NowUtc;error=$failure;scientific_fault_started=$false})}finally{if(-not$stopped){& minikube stop --profile $Profile|Out-Null};if($bundle-and(Test-Path -LiteralPath $bundle)){Remove-Item -LiteralPath $bundle -Recurse -Force -WhatIf:$false -Confirm:$false}}
if($failure){& pwsh -NoProfile -File(Join-Path $PSScriptRoot 'seal-diagnostic-artifacts.ps1')-ArtifactRoot $root -Mode Create;throw "diagnostic_failed:$failure"};$verify=@(& pwsh -NoProfile -File(Join-Path $PSScriptRoot 'verify-host-network-portability-diagnostic.ps1')-ArtifactRoot $root -ExpectedDiagnosticId $DiagnosticId 2>&1);$verifyExit=$LASTEXITCODE;$verify|ForEach-Object{Write-Output ([string]$_)};& pwsh -NoProfile -File(Join-Path $PSScriptRoot 'seal-diagnostic-artifacts.ps1')-ArtifactRoot $root -Mode Create;if($verifyExit){throw 'semantic_verifier_failed'};Write-Output "wifi_host_network_portability_diagnostic=completed id=$DiagnosticId"
