[CmdletBinding(SupportsShouldProcess=$true,ConfirmImpact='High')]
param([string]$RunId='ob-network-resource-compat-003',[string]$Profile='p0-online-boutique',[string]$PythonPath='python',[switch]$ExecutionApproved)
$ErrorActionPreference='Stop';Set-StrictMode -Version Latest
. (Join-Path $PSScriptRoot 'env.ps1');. (Join-Path $PSScriptRoot 'kubernetes-optional-property.ps1');. (Join-Path $PSScriptRoot 'host-event-recordid.ps1');. (Join-Path $PSScriptRoot 'native-json-command.ps1')
$repo=(Resolve-Path(Join-Path $PSScriptRoot '..\..')).Path;$ns='online-boutique';$base=Join-Path $repo 'p0-env\config\online-boutique';$overlay=Join-Path $repo 'p0-env\config\network-delay-resource-compatibility';$root=Join-Path $repo "p0-env\artifacts\P2-NETWORK-DELAY-RESOURCE-COMPAT-001\$RunId";$faultProfile=Join-Path $repo 'p0-env\config\faults\network-delay-recommendation-productcatalog-v1.json';$portForward=$null;$rolledBack=$false;$stopped=$false
function NowUtc{[datetimeoffset]::UtcNow.ToString('yyyy-MM-ddTHH:mm:ss.fffffffZ')}
function WriteJson([string]$Path,[object]$Value){New-Item -ItemType Directory -Path(Split-Path -Parent $Path)-Force|Out-Null;[IO.File]::WriteAllText($Path,($Value|ConvertTo-Json -Depth 60),[Text.UTF8Encoding]::new($false))}
function KJson([string[]]$Args){Invoke-NativeJsonCommand -FilePath (Get-Command kubectl -CommandType Application | Select-Object -First 1).Source -ArgumentList $Args -Operation 'kubectl_json_failed' -DiagnosticPath (Join-Path $root 'kubectl-stderr.log')}
function CaptureText([string]$Name,[scriptblock]$Command){$text=@(&$Command 2>&1)|ForEach-Object{[string]$_};[IO.File]::WriteAllLines((Join-Path $root $Name),$text,[Text.UTF8Encoding]::new($false))}
function PodView{$pods=KJson @('-n',$ns,'get','pods','-l','app=recommendationservice','-o','json');@($pods.items|ForEach-Object{[ordered]@{name=[string]$_.metadata.name;uid=[string]$_.metadata.uid;deletion_timestamp=(Get-KubernetesOptionalProperty $_.metadata 'deletionTimestamp');phase=[string]$_.status.phase;conditions=@($_.status.conditions|ForEach-Object{[ordered]@{type=[string]$_.type;status=[string]$_.status;reason=(Get-KubernetesOptionalProperty $_ 'reason')}});containers=@($_.status.containerStatuses|ForEach-Object{[ordered]@{name=[string]$_.name;ready=[bool]$_.ready;started=(Get-KubernetesOptionalProperty $_ 'started');restart_count=[int]$_.restartCount;container_id=[string]$_.containerID;state=(Get-KubernetesOptionalProperty $_ 'state');last_state=(Get-KubernetesOptionalProperty $_ 'lastState')}})}})}
function Observe([int]$Seconds,[string]$Name,[switch]$RequireStable){$start=[datetimeoffset]::UtcNow;$deadline=$start.AddSeconds($Seconds);$rows=@();do{$view=@(PodView);$rows+=,[ordered]@{observed_utc=NowUtc;pods=$view};if($RequireStable){$active=@($view|Where-Object{$null-eq$_.deletion_timestamp});if($active.Count-ne1){throw "stability_active_pod_count:$($active.Count)"};$c=@($active[0].containers);if(($c.name|Sort-Object)-join','-ne'network-delay-proxy,server'-or@($c|Where-Object{-not$_.ready-or$_.restart_count-ne0}).Count){throw 'stability_container_contract_failed'}};Start-Sleep -Seconds 5}while([datetimeoffset]::UtcNow-lt$deadline);WriteJson(Join-Path $root "$Name.json")([ordered]@{duration_seconds=$Seconds;poll_seconds=5;started_utc=$start.ToString('o');ended_utc=NowUtc;observations=$rows});$rows}
function QueryProm([string]$Start,[string]$End){$names='container_cpu_usage_seconds_total|container_cpu_cfs_periods_total|container_cpu_cfs_throttled_periods_total|container_cpu_cfs_throttled_seconds_total|container_memory_working_set_bytes|container_memory_rss|container_memory_usage_bytes|container_memory_failcnt|container_oom_events_total|container_pressure_cpu_stalled_seconds_total|container_pressure_cpu_waiting_seconds_total|container_pressure_memory_stalled_seconds_total|container_pressure_memory_waiting_seconds_total';$q='{experiment_run_id="ob-netdelay-15u-005",namespace="online-boutique",pod=~"recommendationservice-.*",container="server",__name__=~"'+$names+'"}';$path='/api/v1/namespaces/online-boutique/services/http:prometheus:9090/proxy/api/v1/query_range?query='+[uri]::EscapeDataString($q)+'&start='+[uri]::EscapeDataString($Start)+'&end='+[uri]::EscapeDataString($End)+'&step=5';$r=KJson @('get','--raw',$path);if($r.status-ne'success'-or$r.data.resultType-ne'matrix'){throw 'prometheus_query_failed'};WriteJson(Join-Path $root 'prometheus-resource-metrics.json')$r}
function Rollback{& minikube kubectl --profile $Profile -- apply -k $base|Out-Null;if($LASTEXITCODE){throw 'rollback_apply_failed'};& minikube kubectl --profile $Profile -- -n $ns rollout status deployment/recommendationservice --timeout=10m|Out-Null;if($LASTEXITCODE){throw 'rollback_rollout_failed'};& minikube kubectl --profile $Profile -- -n $ns delete configmap network-delay-proxy-config --ignore-not-found=true|Out-Null;$d=KJson @('-n',$ns,'get','deployment/recommendationservice','-o','json');$c=@($d.spec.template.spec.containers);$addr=@($c[0].env|Where-Object{$_.name-eq'PRODUCT_CATALOG_SERVICE_ADDR'});$ok=$c.Count-eq1-and$c[0].name-eq'server'-and$addr[0].value-eq'productcatalogservice:3550';WriteJson(Join-Path $root 'rollback.json')([ordered]@{verified_utc=NowUtc;passed=$ok;containers=@($c.name);address=[string]$addr[0].value});if(-not$ok){throw 'rollback_contract_failed'};$script:rolledBack=$true}
if(-not$ExecutionApproved){throw 'explicit_execution_approval_required'};if($RunId-ne'ob-network-resource-compat-003'){throw 'unexpected_run_id'};if(@(& git -C $repo status --porcelain).Count){throw 'working_tree_not_clean'};if(Test-Path $root){throw 'immutable_output_exists'};if(-not$PSCmdlet.ShouldProcess($RunId,'run no-toxic resource compatibility gate')){return};New-Item -ItemType Directory -Path $root|Out-Null;$boundary=New-HostEventRecordIdBoundary;WriteJson(Join-Path $root 'host-before.json')$boundary
try{& pwsh -NoProfile -File (Join-Path $PSScriptRoot 'deploy.ps1');if($LASTEXITCODE){throw 'deploy_failed'};& pwsh -NoProfile -File (Join-Path $PSScriptRoot 'verify-active-run-id.ps1') -ExpectedRunId 'ob-netdelay-15u-005';if($LASTEXITCODE){throw 'run_id_gate_failed'};& pwsh -NoProfile -File (Join-Path $PSScriptRoot 'verify-active-workload-profile.ps1') -ExpectedProfileRelative 'p0-env/config/workloads/ob-second-15u-1r-v1.json';if($LASTEXITCODE){throw 'workload_gate_failed'};& minikube kubectl --profile $Profile -- apply -k $overlay|Out-Null;if($LASTEXITCODE){throw 'overlay_apply_failed'};& minikube kubectl --profile $Profile -- -n $ns rollout status deployment/recommendationservice --timeout=10m|Out-Null;if($LASTEXITCODE){throw 'overlay_rollout_failed'};$d=KJson @('-n',$ns,'get','deployment/recommendationservice','-o','json');WriteJson(Join-Path $root 'deployment.json')$d;$c=@($d.spec.template.spec.containers);if($c.Count-ne2-or$c[0].name-ne'server'-or$c[0].resources.limits.cpu-ne'500m'-or$c[0].resources.requests.cpu-ne'100m'-or$c[0].livenessProbe.grpc.port-ne8080-or$c[0].livenessProbe.periodSeconds-ne5){throw 'live_resource_probe_contract_failed'};WriteJson(Join-Path $root 'node-before.json')(KJson @('get','node','p0-online-boutique','-o','json'))
    $exe=(Get-Command minikube).Source;$portForward=Start-Process -FilePath $exe -ArgumentList @('kubectl','--profile',$Profile,'--','-n',$ns,'port-forward','deployment/recommendationservice','18474:8474') -PassThru -WindowStyle Hidden -RedirectStandardOutput (Join-Path $root 'port-forward.stdout.log') -RedirectStandardError (Join-Path $root 'port-forward.stderr.log');Start-Sleep -Seconds 4;& $PythonPath (Join-Path $PSScriptRoot 'manage-network-delay-proxy.py') --api-base http://127.0.0.1:18474 --profile $faultProfile --action verify-clean --evidence (Join-Path $root 'proxy-clean-before.json');if($LASTEXITCODE){throw 'proxy_clean_before_failed'}
    Observe 120 'target-stability' -RequireStable|Out-Null;$start=NowUtc;Observe 180 'pod-observations' -RequireStable|Out-Null;$end=NowUtc;QueryProm $start $end;& $PythonPath (Join-Path $PSScriptRoot 'manage-network-delay-proxy.py') --api-base http://127.0.0.1:18474 --profile $faultProfile --action verify-clean --evidence (Join-Path $root 'proxy-clean-after.json');if($LASTEXITCODE){throw 'proxy_clean_after_failed'}
    WriteJson(Join-Path $root 'events.json')(KJson @('-n',$ns,'get','events','--field-selector','involvedObject.kind=Pod','-o','json'));WriteJson(Join-Path $root 'node-after.json')(KJson @('get','node','p0-online-boutique','-o','json'));$pod=@((PodView)|Where-Object{$null-eq$_.deletion_timestamp})[0].name;CaptureText 'pod-describe.txt' {& minikube kubectl --profile $Profile -- -n $ns describe pod $pod};foreach($name in @('server','network-delay-proxy')){CaptureText "$name-current.log" {& minikube kubectl --profile $Profile -- -n $ns logs $pod -c $name --timestamps=true}}
    if($portForward-and-not$portForward.HasExited){Stop-Process $portForward.Id -Force};$portForward=$null;Rollback;& minikube stop --profile $Profile|Out-Null;$stopped=$true;WriteJson(Join-Path $root 'host-after.json')(Measure-HostEventsAfterRecordIdBoundary $boundary);Write-Output "network_resource_compatibility=completed run_id=$RunId"
}catch{WriteJson(Join-Path $root 'run-error.json')([ordered]@{failed_utc=NowUtc;error=$_.Exception.Message;scientific_fault_started=$false});throw}finally{if($portForward-and-not$portForward.HasExited){Stop-Process $portForward.Id -Force -ErrorAction SilentlyContinue};if(-not$rolledBack){try{Rollback}catch{WriteJson(Join-Path $root 'rollback-error.json')([ordered]@{failed_utc=NowUtc;error=$_.Exception.Message})}};if(-not$stopped){& minikube stop --profile $Profile|Out-Null};if(-not(Test-Path(Join-Path $root 'host-after.json'))){try{WriteJson(Join-Path $root 'host-after.json')(Measure-HostEventsAfterRecordIdBoundary $boundary)}catch{WriteJson(Join-Path $root 'host-after-error.json')([ordered]@{failed_utc=NowUtc;error=$_.Exception.Message})}}}
