$ErrorActionPreference='Stop';Set-StrictMode -Version Latest
$runner=Get-Content -LiteralPath(Join-Path $PSScriptRoot 'run-network-base-readiness-diagnostic.ps1')-Raw
foreach($required in @('[Parameter(Mandatory)][string]$DiagnosticId','[Parameter(Mandatory)][string]$RuntimeStateRoot','[Parameter(Mandatory)][string]$OnlineBoutiqueSourceRoot','explicit_diagnostic_approval_required','closed_diagnostic_id','no_preregistered_diagnostic_id','ob-network-base-readiness-008','ob-network-base-readiness-009','ob-network-base-readiness-010','unexpected_profile','working_tree_not_clean','immutable_diagnostic_output_exists','runtime_state_root_missing','convergence_timeout_seconds=900','stability_duration_seconds=180','poll_seconds=5','ob-default-10u-1r-v1','proxy_overlay_applied=$false','toxic_created=$false','scientific_fault_started=$false','scientific_window_started=$false','New-HostEventRecordIdBoundary','Measure-HostEventsAfterRecordIdBoundary','if($failure)','seal-diagnostic-artifacts.ps1','verify-network-base-readiness-diagnostic.ps1','minikube stop','online_boutique_source_missing','online_boutique_source_revision_unreadable','online_boutique_source_revision_mismatch','5b3a712ab85ccb8f6f7cd5b720d36ba9a8d041eb','ConvertTo-KubernetesPodView','semantic_verifier_failed','$verifierExit=$LASTEXITCODE','AssertStoppedRecoveredProfile','AssertSshKeyCongruence','New-SourceBoundDeploymentBundle','upstream-base','base_overlay_source_reference_contract_mismatch','deployment-bundle-provenance.json','relative_checkout_source_reference_used=$false','New-Item -ItemType Directory -Path $tempRoot -WhatIf:$false -Confirm:$false','container_authorized_keys_read_failed','ssh_key_provenance_mismatch','exact_host_public_key_present','86bf057eb0bf9488079879a62c297157bd9e0b2a835b9097dc9d61b79d7e02b1','SHA256:E8X6DYnpxGPJpp3lUOnbtLCow0oNNLC9HomdrrWBEOs','recovered_profile_config_missing','recovered_profile_contract_mismatch','recovered_profile_container_state_mismatch','recovered_profile_volume_missing','preflight-provenance.json','09bf0e077f291318df561f16e48d38cc805ebcd7','39f00a9317341b41d889fe79c6a5893e564d5954','native-command-capture.ps1','Invoke-NativeCommandCapture','minikube-start.json')){if(-not$runner.Contains($required)){throw "base_readiness_runner_contract_missing:$required"}}
if($runner.Contains('.containerID')-or$runner.Contains('.containerStatuses')){throw 'base_readiness_runner_direct_optional_property_access'}
$verifierInvoke=$runner.IndexOf('$verifierOutput=@(& pwsh');$exitCapture=$runner.IndexOf('$verifierExit=$LASTEXITCODE');$exitGuard=$runner.IndexOf('if($verifierExit-ne0)');$completed=$runner.IndexOf('network_base_readiness_diagnostic=completed');if($verifierInvoke-lt0-or$exitCapture-le$verifierInvoke-or$exitGuard-le$exitCapture-or$completed-le$exitGuard){throw 'semantic_verifier_exit_gate_order_failed'}
if($runner.Contains("throw'")-or$runner.Contains('throw"')){throw 'base_readiness_runner_unsafe_throw_tokenization'}
$sourceGuard=$runner.IndexOf("`nAssertPinnedSource");$profileGuard=$runner.IndexOf("`n`$preflight=AssertStoppedRecoveredProfile");$artifactCreate=$runner.IndexOf('New-Item -ItemType Directory -Path $root');$start=$runner.IndexOf('$startCapture=Invoke-NativeCommandCapture');if($sourceGuard-lt0-or$profileGuard-le$sourceGuard-or$artifactCreate-le$profileGuard-or$start-le$artifactCreate){throw 'portability_preflight_order_failed'}
$captureInvoke=$runner.IndexOf('$startCapture=Invoke-NativeCommandCapture');$captureWrite=$runner.IndexOf("WriteJson(Join-Path `$root 'minikube-start.json')");$captureGuard=$runner.IndexOf("if(`$startCapture.exit_code-ne0)");if($captureInvoke-lt0-or$captureWrite-le$captureInvoke-or$captureGuard-le$captureWrite){throw 'minikube_start_capture_order_failed'}
$verifier=Get-Content -LiteralPath(Join-Path $PSScriptRoot 'verify-network-base-readiness-diagnostic.ps1')-Raw
if(-not$verifier.Contains('$hostEvidence=ReadJson')-or$verifier.Contains('$host=ReadJson')){throw 'verifier_host_variable_contract_failed'}
$prereg=Get-Content -LiteralPath(Join-Path $PSScriptRoot '..\artifacts\P2-NETWORK-DELAY-BASE-READINESS-DIAG-001\ob-network-base-readiness-010-preregistration.md')-Raw
foreach($required in @('ob-network-base-readiness-010','900 sn','180 sn / 5 sn','toxic/fault: yasak','D-067 headroom','canonical merge','runtime','D-099','39f00a9317341b41d889fe79c6a5893e564d5954','semantic verifier','5b3a712ab85ccb8f6f7cd5b720d36ba9a8d041eb','source-bound','temporary deployment bundle','authorized_keys')){if(-not$prereg.Contains($required)){throw "base_readiness_prereg_contract_missing:$required"}}
Write-Output 'network_base_readiness_contract_tests=passed'
