#!/usr/bin/env python3
import hashlib,importlib.util,json,subprocess,tempfile
from pathlib import Path
SCRIPT=Path(__file__).with_name('verify-network-delay-headroom-normal-metadata.py');SPEC=importlib.util.spec_from_file_location('v',SCRIPT);V=importlib.util.module_from_spec(SPEC);SPEC.loader.exec_module(V)
def write(root,name,value):
 p=root/name;p.parent.mkdir(parents=True,exist_ok=True);p.write_text(json.dumps(value)+'\n',encoding='utf-8');return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 with tempfile.TemporaryDirectory() as d:
  root=Path(d)/'repo';root.mkdir();subprocess.run(['git','init','-q',str(root)],check=True);subprocess.run(['git','-C',str(root),'config','user.email','fixture@invalid'],check=True);subprocess.run(['git','-C',str(root),'config','user.name','fixture'],check=True)
  run='ob-netdelay-500m-normal-15u-001';wh=write(root,'workload.json',{'profile_id':'ob-second-15u-1r-v1'});sh=write(root,'slo.json',{'slo_id':'p2-network-delay-001-slo-v1'});clean={'run_id':run,'scientific_fault_started':False,'after':{'toxics':[]}};preh=write(root,'pre.json',clean);posth=write(root,'post.json',clean);mh=write(root,'manifestation.json',{'run_id':run,'failure_manifestation':None});ah=write(root,'analysis.json',{'run_id':run,'valid_headroom_input':True,'run_level_upper_tail_ms':100.0});subprocess.run(['git','-C',str(root),'add','.'],check=True);subprocess.run(['git','-C',str(root),'commit','-qm','fixture'],check=True);rev=subprocess.check_output(['git','-C',str(root),'rev-parse','HEAD'],text=True).strip()
  m={'run_id':run,'workload_profile_id':'ob-second-15u-1r-v1','experiment_id':'P2-NETWORK-DELAY-HEADROOM-001','run_kind':'network_delay_normal_baseline','fault_class':'normal','scientific_fault_started':False,'normal_topology':'no_toxic_proxy_overlay','resources':{'server_cpu_limit':'500m','server_cpu_request':'100m','proxy_cpu_limit':'100m'},'workload_profile_path':'workload.json','workload_profile_sha256':wh,'slo_path':'slo.json','slo_sha256':sh,'proxy_clean_pre_evidence_path':'pre.json','proxy_clean_pre_evidence_sha256':preh,'proxy_clean_post_evidence_path':'post.json','proxy_clean_post_evidence_sha256':posth,'manifestation_evidence_path':'manifestation.json','manifestation_evidence_sha256':mh,'headroom_input_path':'analysis.json','headroom_input_sha256':ah,'failure_manifestation':None,'phases':{'warmup_start_utc':'2026-01-01T00:00:00Z','warmup_end_utc':'2026-01-01T00:05:00Z','normal_baseline_start_utc':'2026-01-01T00:05:00Z','normal_baseline_end_utc':'2026-01-01T00:10:00Z'},'host_health':{'whea_event_17_delta':0,'kernel_power_41_delta':0,'bugcheck_delta':0},'runtime_evidence':{'tracked_deployment_count':15,'pod_lifecycle_stable':True,'proxy_clean_pre_verified':True,'proxy_clean_post_verified':True,'rollback_verified':True},'valid_run':True,'code_revision':rev};mp=root/'metadata.json';mp.write_text(json.dumps(m),encoding='utf-8');assert V.verify(root,mp)['verification_passed']
  clean['after']['toxics']=[{'name':'forbidden'}];m['proxy_clean_post_evidence_sha256']=write(root,'post.json',clean);mp.write_text(json.dumps(m),encoding='utf-8');r=V.verify(root,mp);assert not r['verification_passed'] and any(x['name']=='proxy_clean' and not x['passed'] for x in r['checks'])
 print('network_delay_headroom_normal_metadata_positive=passed');print('network_delay_headroom_normal_metadata_toxic_negative=passed');return 0
if __name__=='__main__':raise SystemExit(main())
