$ErrorActionPreference='Stop';Set-StrictMode -Version Latest
$runner=Get-Content -LiteralPath(Join-Path $PSScriptRoot 'run-minikube-state-postmortem.ps1')-Raw
foreach($required in @("DiagnosticId='ob-minikube-state-postmortem-001'",'externalMinikubeHome','resolvedMinikubeHome','expectedMinikubeHome','resolved_minikube_home','explicit_state_postmortem_approval_required','working_tree_not_clean','immutable_diagnostic_output_exists','resolved_minikube_home_mismatch','docker_engine_not_ready','exact_profile_container_missing','profile_container_not_stopped','profile_deleted=$false','container_started=$false','cluster_started=$false','application_manifest_applied=$false','workload_started=$false','toxic_created=$false','scientific_fault_started=$false','scientific_window_started=$false','verify-minikube-state-postmortem.ps1','seal-diagnostic-artifacts.ps1')){if(-not$runner.Contains($required)){throw "state_postmortem_runner_contract_missing:$required"}}
foreach($forbidden in @('minikube start','minikube delete','docker start','docker restart','docker rm','docker volume rm','apply -k','manage-network-delay-proxy','toxic add')){if($runner.Contains($forbidden)){throw "state_postmortem_forbidden_mutation:$forbidden"}}
$verifier=Get-Content -LiteralPath(Join-Path $PSScriptRoot 'verify-minikube-state-postmortem.ps1')-Raw
foreach($required in @('P2-MINIKUBE-STATE-POSTMORTEM-001','state_root_provenance_mismatch','postmortem_scope_mismatch','postmortem_container_was_running','postmortem_evidence_missing','stopped_state_postmortem_captured','assessment_contract_mismatch')){if(-not$verifier.Contains($required)){throw "state_postmortem_verifier_contract_missing:$required"}}
$prereg=Get-Content -LiteralPath(Join-Path $PSScriptRoot '..\artifacts\P2-MINIKUBE-STATE-POSTMORTEM-001\ob-minikube-state-postmortem-001-preregistration.md')-Raw
foreach($required in @('ob-minikube-state-postmortem-001','read-only','resolved MINIKUBE_HOME','Profile delete','cluster start','canonical merge','runtime approval')){if(-not$prereg.Contains($required)){throw "state_postmortem_prereg_contract_missing:$required"}}
Write-Output 'minikube_state_postmortem_contract_tests=passed'
