$ErrorActionPreference='Stop';Set-StrictMode -Version Latest
$root=Join-Path ([IO.Path]::GetTempPath()) 'ob-host-network-portability-wifi-001';if(Test-Path $root){Remove-Item -LiteralPath $root -Recurse -Force};New-Item -ItemType Directory -Path $root|Out-Null
function WriteJson([string]$Name,$Value){[IO.File]::WriteAllText((Join-Path $root $Name),($Value|ConvertTo-Json -Depth 20),[Text.UTF8Encoding]::new($false))}
$network=[ordered]@{transport='wifi';adapter_name='Wi-Fi';interface_description='fixture';interface_index=7;driver_version='1.0';default_route_present=$true;privacy_contract='ssid_bssid_mac_ip_gateway_omitted'};$hostEvidence=[ordered]@{passed=$true;counts=[ordered]@{whea_event_17=0;kernel_power_41=0;bugcheck=0}}
WriteJson 'diagnostic-manifest.json' ([ordered]@{diagnostic_id='ob-host-network-portability-wifi-001';gate_id='P1-HOST-NETWORK-PORTABILITY-001';transport='wifi';adapter_name='Wi-Fi';interface_description='fixture';driver_version='1.0';scientific_fault_started=$false})
WriteJson 'clean-boot-preflight.json' ([ordered]@{passed=$true;docker_ready=$true;free_space_bytes=[int64](20GB);free_space_gate_bytes=[int64](15GB);events_since_boot=[ordered]@{whea_event_17=0;kernel_power_41=0;bugcheck=0};profile_status=[ordered]@{host='Stopped';kubelet='Stopped';api_server='Stopped'}})
WriteJson 'global-host-after.json' $hostEvidence
$uids=@('a','b','c');$names=@('active-load-window-1','active-load-window-2','e2e-window');$durations=@(1800,1800,600);for($i=0;$i-lt3;$i++){WriteJson "$($names[$i]).json" ([ordered]@{duration_seconds=$durations[$i];loadgenerator_uid=$uids[$i];network_before=$network;network_after=$network;network_stable=$true;host_events=$hostEvidence;application_telemetry_closure_passed=($i-eq2)})}
WriteJson 'assessment.json' ([ordered]@{diagnostic_id='ob-host-network-portability-wifi-001';classification='wifi_host_portability_supported';passed=$true;transport='wifi';adapter_name='Wi-Fi';interface_description='fixture';driver_version='1.0';active_load_windows_completed=2;active_load_window_seconds=@(1800,1800);e2e_closure_seconds=600;application_telemetry_closure_passed=$true;offline_receipt_verification_passed=$true;host_event_windows=@($hostEvidence.counts,$hostEvidence.counts,$hostEvidence.counts)})
[IO.File]::WriteAllText((Join-Path $root 'e2e-close-output.txt'),"finalized_run_verification=passed`nclose_run=passed",[Text.UTF8Encoding]::new($false));[IO.File]::WriteAllText((Join-Path $root 'offline-receipt-verification.txt'),'finalized_run_verification=passed',[Text.UTF8Encoding]::new($false));try{$out=@(& powershell -NoProfile -ExecutionPolicy Bypass -File(Join-Path $PSScriptRoot 'verify-host-network-portability-diagnostic.ps1')-ArtifactRoot $root -ExpectedDiagnosticId 'ob-host-network-portability-wifi-001' 2>&1);if($LASTEXITCODE-or-not(($out-join"`n").Contains('host_network_portability_verification=passed'))){throw'wifi_portability_verifier_positive_failed'};$bad=Get-Content(Join-Path $root 'assessment.json')-Raw|ConvertFrom-Json;$bad|Add-Member ssid private;WriteJson 'assessment.json' $bad;$previous=$ErrorActionPreference;$ErrorActionPreference='Continue';try{$negative=@(& powershell -NoProfile -ExecutionPolicy Bypass -File(Join-Path $PSScriptRoot 'verify-host-network-portability-diagnostic.ps1')-ArtifactRoot $root -ExpectedDiagnosticId 'ob-host-network-portability-wifi-001' 2>&1);$negativeExit=$LASTEXITCODE}finally{$ErrorActionPreference=$previous};if($negativeExit-eq0-or-not(($negative-join"`n").Contains('forbidden_network_identifier'))){throw'wifi_portability_verifier_privacy_negative_failed'}}finally{Remove-Item -LiteralPath $root -Recurse -Force}
Write-Output 'wifi_portability_verifier_positive=passed';Write-Output 'wifi_portability_verifier_privacy_negative=passed'
