$ErrorActionPreference='Stop';Set-StrictMode -Version Latest
$runner=Get-Content -LiteralPath(Join-Path $PSScriptRoot 'run-network-base-readiness-diagnostic.ps1')-Raw
foreach($required in @("DiagnosticId='ob-network-base-readiness-007'",'explicit_diagnostic_approval_required','working_tree_not_clean','immutable_diagnostic_output_exists','convergence_timeout_seconds=900','stability_duration_seconds=180','poll_seconds=5','ob-default-10u-1r-v1','proxy_overlay_applied=$false','toxic_created=$false','scientific_fault_started=$false','scientific_window_started=$false','New-HostEventRecordIdBoundary','Measure-HostEventsAfterRecordIdBoundary','if($failure)','seal-diagnostic-artifacts.ps1','verify-network-base-readiness-diagnostic.ps1','minikube stop','online_boutique_source_missing','online_boutique_source_revision_unreadable','online_boutique_source_revision_mismatch','5b3a712ab85ccb8f6f7cd5b720d36ba9a8d041eb','ConvertTo-KubernetesPodView','semantic_verifier_failed','$verifierExit=$LASTEXITCODE')){if(-not$runner.Contains($required)){throw "base_readiness_runner_contract_missing:$required"}}
if($runner.Contains('.containerID')-or$runner.Contains('.containerStatuses')){throw 'base_readiness_runner_direct_optional_property_access'}
$verifierInvoke=$runner.IndexOf('$verifierOutput=@(& pwsh');$exitCapture=$runner.IndexOf('$verifierExit=$LASTEXITCODE');$exitGuard=$runner.IndexOf('if($verifierExit-ne0)');$completed=$runner.IndexOf('network_base_readiness_diagnostic=completed');if($verifierInvoke-lt0-or$exitCapture-le$verifierInvoke-or$exitGuard-le$exitCapture-or$completed-le$exitGuard){throw 'semantic_verifier_exit_gate_order_failed'}
if($runner.Contains("throw'")-or$runner.Contains('throw"')){throw 'base_readiness_runner_unsafe_throw_tokenization'}
$sourceGuard=$runner.IndexOf("`n AssertPinnedSource");$start=$runner.IndexOf('& minikube start');if($sourceGuard-lt0-or$start-lt0-or$sourceGuard-ge$start){throw 'source_preflight_must_precede_cluster_start'}
$verifier=Get-Content -LiteralPath(Join-Path $PSScriptRoot 'verify-network-base-readiness-diagnostic.ps1')-Raw
if(-not$verifier.Contains('$hostEvidence=ReadJson')-or$verifier.Contains('$host=ReadJson')){throw 'verifier_host_variable_contract_failed'}
$prereg=Get-Content -LiteralPath(Join-Path $PSScriptRoot '..\artifacts\P2-NETWORK-DELAY-BASE-READINESS-DIAG-001\ob-network-base-readiness-007-preregistration.md')-Raw
foreach($required in @('ob-network-base-readiness-007','900 sn','180 sn / 5 sn','toxic/fault: yasak','D-067 headroom','canonical merge','runtime','D-088','semantic verifier','5b3a712ab85ccb8f6f7cd5b720d36ba9a8d041eb')){if(-not$prereg.Contains($required)){throw "base_readiness_prereg_contract_missing:$required"}}
Write-Output 'network_base_readiness_contract_tests=passed'
