#!/usr/bin/env python3
import copy,hashlib,importlib.util,json,subprocess,tempfile
from pathlib import Path
SCRIPT=Path(__file__).with_name('verify-network-delay-headroom-normal-metadata.py');SPEC=importlib.util.spec_from_file_location('v',SCRIPT);V=importlib.util.module_from_spec(SPEC);SPEC.loader.exec_module(V)
def write(root,name,value):
 p=root/name;p.parent.mkdir(parents=True,exist_ok=True);p.write_text(json.dumps(value)+'\n',encoding='utf-8');return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 with tempfile.TemporaryDirectory() as d:
  root=Path(d)/'repo';root.mkdir();subprocess.run(['git','init','-q',str(root)],check=True);subprocess.run(['git','-C',str(root),'config','user.email','fixture@invalid'],check=True);subprocess.run(['git','-C',str(root),'config','user.name','fixture'],check=True)
  run='ob-netdelay-500m-normal-15u-006';wh=write(root,'workload.json',{'profile_id':'ob-second-15u-1r-v1'});sh=write(root,'slo.json',{'slo_id':'p2-network-delay-001-slo-v1'});clean={'run_id':run,'scientific_fault_started':False,'after':{'toxics':[]}};preh=write(root,'pre.json',clean);posth=write(root,'post.json',clean);mh=write(root,'manifestation.json',{'run_id':run,'failure_manifestation':None});ah=write(root,'analysis.json',{'run_id':run,'valid_headroom_input':True,'run_level_upper_tail_ms':100.0});subprocess.run(['git','-C',str(root),'add','.'],check=True);subprocess.run(['git','-C',str(root),'commit','-qm','fixture'],check=True);rev=subprocess.check_output(['git','-C',str(root),'rev-parse','HEAD'],text=True).strip()
  m={'run_id':run,'workload_profile_id':'ob-second-15u-1r-v1','random_seed':1,'experiment_id':'P2-NETWORK-DELAY-HEADROOM-001','run_kind':'network_delay_normal_baseline','fault_class':'normal','scientific_fault_started':False,'normal_topology':'no_toxic_proxy_overlay','resources':{'server_cpu_limit':'500m','server_cpu_request':'100m','proxy_cpu_limit':'100m'},'workload_profile_path':'workload.json','workload_profile_sha256':wh,'slo_path':'slo.json','slo_sha256':sh,'proxy_clean_pre_evidence_path':'pre.json','proxy_clean_pre_evidence_sha256':preh,'proxy_clean_post_evidence_path':'post.json','proxy_clean_post_evidence_sha256':posth,'manifestation_evidence_path':'manifestation.json','manifestation_evidence_sha256':mh,'headroom_input_path':'analysis.json','headroom_input_sha256':ah,'failure_manifestation':None,'phases':{'warmup_start_utc':'2026-01-01T00:00:00Z','warmup_end_utc':'2026-01-01T00:05:00Z','normal_baseline_start_utc':'2026-01-01T00:05:00Z','normal_baseline_end_utc':'2026-01-01T00:10:00Z'},'host_health':{'whea_event_17_delta':0,'kernel_power_41_delta':0,'bugcheck_delta':0},'host_network':{'transport':'ethernet','adapter_name':'Ethernet','interface_description':'fixture','interface_index':5,'driver_version':'1.0','stable':True,'privacy_contract':'ssid_bssid_mac_ip_gateway_omitted'},'runtime_evidence':{'tracked_deployment_count':15,'pod_lifecycle_stable':True,'proxy_clean_pre_verified':True,'proxy_clean_post_verified':True,'rollback_verified':True},'valid_run':True,'code_revision':rev};mp=root/'metadata.json';mp.write_text(json.dumps(m),encoding='utf-8');assert V.verify(root,mp)['verification_passed']
  original=copy.deepcopy(m)
  m['run_id']='ob-netdelay-500m-normal-10u-005';m['workload_profile_id']='ob-default-10u-1r-v1'
  clean['run_id']=m['run_id'];m['proxy_clean_pre_evidence_sha256']=write(root,'pre.json',clean);m['proxy_clean_post_evidence_sha256']=write(root,'post.json',clean)
  ep='p0-env/artifacts/P2-NETWORK-DELAY-HEADROOM-001/ob-netdelay-500m-normal-10u-005/ethernet-preflight.json'
  e={'decision_id':'D-110','passed':True,'source_clean':True,'source_revision':'5b3a712ab85ccb8f6f7cd5b720d36ba9a8d041eb','source_root':'C:/fixture/source','runtime_state_root':'C:/fixture/state','wireless_disabled_or_absent':True,'events_since_boot':{'whea_event_17':0,'kernel_power_41':0,'bugcheck':0},'free_space_bytes':16*1024**3,'minimum_free_space_bytes':15*1024**3,'docker_ready':True,'profile':'p0-online-boutique','profile_status_native_exit_code':7,'profile_status':{'Host':'Stopped','Kubelet':'Stopped','APIServer':'Stopped'},'network':dict(m['host_network'],default_route_present=True)}
  m['ethernet_preflight_path']=ep;m['ethernet_preflight_sha256']=write(root,ep,e);mp.write_text(json.dumps(m),encoding='utf-8');assert V.verify(root,mp)['verification_passed']
  for key,value in [('wireless_disabled_or_absent',False),('free_space_bytes',14*1024**3),('source_revision','wrong'),('events_since_boot',{'whea_event_17':12,'kernel_power_41':0,'bugcheck':0})]:
   bad=copy.deepcopy(e);bad[key]=value;m['ethernet_preflight_sha256']=write(root,ep,bad);mp.write_text(json.dumps(m),encoding='utf-8');assert any(x['name']=='d110_ethernet_preflight' and not x['passed'] for x in V.verify(root,mp)['checks'])
  m['ethernet_preflight_sha256']=write(root,ep,e);m['host_network']['transport']='wifi';mp.write_text(json.dumps(m),encoding='utf-8');assert any(x['name']=='d110_ethernet_preflight' and not x['passed'] for x in V.verify(root,mp)['checks'])
  m=original;clean['run_id']=run;write(root,'pre.json',clean);write(root,'post.json',clean)
  print('d110_metadata_preflight=passed positive=1 negative=5')
  clean['after']['toxics']=[{'name':'forbidden'}];m['proxy_clean_post_evidence_sha256']=write(root,'post.json',clean);mp.write_text(json.dumps(m),encoding='utf-8');r=V.verify(root,mp);assert not r['verification_passed'] and any(x['name']=='proxy_clean' and not x['passed'] for x in r['checks'])
  m['host_network']['ssid']='private';mp.write_text(json.dumps(m),encoding='utf-8');r=V.verify(root,mp);assert not r['verification_passed'] and any(x['name']=='host_network' and not x['passed'] for x in r['checks'])
 print('network_delay_headroom_normal_metadata_positive=passed');print('network_delay_headroom_normal_metadata_toxic_negative=passed');return 0
if __name__=='__main__':raise SystemExit(main())
