[CmdletBinding()]
param([Parameter(Mandatory)][string]$ArtifactRoot,[Parameter(Mandatory)][string]$ExpectedDiagnosticId)
$ErrorActionPreference='Stop';Set-StrictMode -Version Latest
function ReadJson([string]$Name){$path=Join-Path $ArtifactRoot $Name;if(-not(Test-Path -LiteralPath $path -PathType Leaf)){throw "required_evidence_missing:$Name"};Get-Content -LiteralPath $path -Raw|ConvertFrom-Json}
function AssertPrivateFieldsAbsent($Value){$json=$Value|ConvertTo-Json -Depth 40 -Compress;foreach($field in @('"ssid"','"bssid"','"mac_address"','"ip_address"','"gateway"')){if($json.Contains($field)){throw "forbidden_network_identifier:$field"}}}
if((Split-Path -Leaf $ArtifactRoot.TrimEnd('\','/'))-ne$ExpectedDiagnosticId){throw'artifact_identity_mismatch'}
$manifest=ReadJson 'diagnostic-manifest.json';if($manifest.diagnostic_id-ne$ExpectedDiagnosticId-or$manifest.gate_id-ne'P1-HOST-NETWORK-PORTABILITY-001'-or$manifest.transport-ne'wifi'-or-not$manifest.adapter_name-or-not$manifest.interface_description-or-not$manifest.driver_version-or[bool]$manifest.scientific_fault_started){throw'manifest_contract_failed'}
$preflight=ReadJson 'clean-boot-preflight.json';if(-not[bool]$preflight.passed-or-not[bool]$preflight.docker_ready-or[int64]$preflight.free_space_bytes-lt[int64]$preflight.free_space_gate_bytes-or[int]$preflight.events_since_boot.whea_event_17-ne0-or[int]$preflight.events_since_boot.kernel_power_41-ne0-or[int]$preflight.events_since_boot.bugcheck-ne0-or$preflight.profile_status.host-ne'Stopped'-or$preflight.profile_status.kubelet-ne'Stopped'-or$preflight.profile_status.api_server-ne'Stopped'){throw'clean_boot_preflight_contract_failed'}
$globalAfter=ReadJson 'global-host-after.json';if(-not[bool]$globalAfter.passed-or[int]$globalAfter.counts.whea_event_17-ne0-or[int]$globalAfter.counts.kernel_power_41-ne0-or[int]$globalAfter.counts.bugcheck-ne0){throw'global_host_gate_failed'}
$windows=@((ReadJson 'active-load-window-1.json'),(ReadJson 'active-load-window-2.json'),(ReadJson 'e2e-window.json'))
$expected=@(1800,1800,600);for($i=0;$i-lt3;$i++){if([double]$windows[$i].duration_seconds-lt$expected[$i]){throw "window_duration_failed:$i"};if(-not[bool]$windows[$i].host_events.passed-or[int]$windows[$i].host_events.counts.whea_event_17-ne0-or[int]$windows[$i].host_events.counts.kernel_power_41-ne0-or[int]$windows[$i].host_events.counts.bugcheck-ne0){throw "window_host_gate_failed:$i"};if(-not[bool]$windows[$i].network_stable-or$windows[$i].network_before.transport-ne'wifi'-or$windows[$i].network_before.adapter_name-ne$manifest.adapter_name-or$windows[$i].network_before.interface_description-ne$manifest.interface_description-or$windows[$i].network_before.driver_version-ne$manifest.driver_version-or$windows[$i].network_before.adapter_name-ne$windows[$i].network_after.adapter_name-or$windows[$i].network_before.interface_description-ne$windows[$i].network_after.interface_description-or$windows[$i].network_before.driver_version-ne$windows[$i].network_after.driver_version){throw "window_network_gate_failed:$i"};AssertPrivateFieldsAbsent $windows[$i]}
if($windows[0].loadgenerator_uid-eq$windows[1].loadgenerator_uid-or$windows[1].loadgenerator_uid-eq$windows[2].loadgenerator_uid){throw'loadgenerator_window_independence_failed'}
$assessment=ReadJson 'assessment.json';if($assessment.diagnostic_id-ne$ExpectedDiagnosticId-or$assessment.classification-ne'wifi_host_portability_supported'-or-not[bool]$assessment.passed-or$assessment.transport-ne'wifi'-or$assessment.adapter_name-ne$manifest.adapter_name-or$assessment.interface_description-ne$manifest.interface_description-or$assessment.driver_version-ne$manifest.driver_version-or[int]$assessment.active_load_windows_completed-ne2-or@($assessment.active_load_window_seconds|Where-Object{[int]$_-ge1800}).Count-ne2-or[int]$assessment.e2e_closure_seconds-lt600-or-not[bool]$assessment.application_telemetry_closure_passed-or-not[bool]$assessment.offline_receipt_verification_passed-or@($assessment.host_event_windows).Count-ne3-or-not[bool]$windows[2].application_telemetry_closure_passed){throw'assessment_contract_failed'};AssertPrivateFieldsAbsent $assessment
$close=Get-Content -LiteralPath(Join-Path $ArtifactRoot 'e2e-close-output.txt')-Raw;if(-not$close.Contains('close_run=passed')-or-not$close.Contains('finalized_run_verification=passed')){throw'e2e_close_gate_failed'}
$offline=Get-Content -LiteralPath(Join-Path $ArtifactRoot 'offline-receipt-verification.txt')-Raw;if(-not$offline.Contains('finalized_run_verification=passed')){throw'offline_receipt_gate_failed'}
Write-Output 'host_network_portability_verification=passed'
