[CmdletBinding()]param([Parameter(Mandatory)][string]$ArtifactRoot,[string]$ExpectedDiagnosticId='ob-k8s-bootstrap-state-consistency-002')
$ErrorActionPreference='Stop';Set-StrictMode -Version Latest
function Read-EvidenceJson([string]$n){Get-Content -LiteralPath(Join-Path $ArtifactRoot $n)-Raw|ConvertFrom-Json}
$leaf=Split-Path -Leaf $ArtifactRoot.TrimEnd([IO.Path]::DirectorySeparatorChar,[IO.Path]::AltDirectorySeparatorChar);if($leaf-ne$ExpectedDiagnosticId){throw 'artifact_root_diagnostic_id_mismatch'}
foreach($n in @('diagnostic-manifest.json','prestart-container-inspect.json','bootstrap-process-observations.json','final-container-inspect-capture.json','minikube-last-start-capture.json','assessment.json','host-after.json')){if(-not(Test-Path -LiteralPath(Join-Path $ArtifactRoot $n))){throw "state_consistency_evidence_missing:$n"}}
$m=Read-EvidenceJson 'diagnostic-manifest.json';if($m.diagnostic_id-ne$ExpectedDiagnosticId-or$m.gate_id-ne'P2-KUBERNETES-BOOTSTRAP-STATE-CONSISTENCY-DIAG-001'){throw 'diagnostic_identity_mismatch'}
if($m.driver-ne'docker'-or$m.kubernetes_version-ne'v1.34.0'-or[int]$m.cpus-ne4-or[int]$m.memory_mib-ne6144-or[int]$m.disk_gib-ne32-or$m.container_runtime-ne'containerd'-or[int]$m.timeout_seconds-ne420-or[int]$m.poll_seconds-ne5){throw 'bootstrap_contract_mismatch'}
if(-not$m.reuses_preserved_profile-or$m.profile_deleted-or$m.application_manifest_applied-or$m.workload_started-or$m.toxic_created-or$m.scientific_fault_started-or$m.dataset_inclusion-or$m.headroom_decision_inclusion){throw 'diagnostic_scope_mismatch'}
$o=Read-EvidenceJson 'bootstrap-process-observations.json';if($null-eq$o.start_exit_code-or@($o.observations).Count-lt1){throw 'start_exit_code_or_observations_missing'}
$a=Read-EvidenceJson 'assessment.json';if($a.classification-notin@('bootstrap_client_timeout_observed','bootstrap_start_succeeded_observed','bootstrap_start_failed_with_state_evidence','bootstrap_start_failed_without_live_container')-or$a.profile_deleted-or-not$a.profile_stopped_after_capture-or$a.application_manifest_applied-or$a.workload_started-or$a.scientific_fault_started-or$a.dataset_inclusion-or$a.headroom_decision_inclusion-or$a.causal_conclusion){throw 'assessment_contract_mismatch'}
if($a.live_container_seen){
 $paths=@('/var/lib/kubelet/kubeadm-flags.env','/var/lib/kubelet/config.yaml','/var/lib/minikube/etcd','/etc/kubernetes/bootstrap-kubelet.conf','/etc/kubernetes/kubelet.conf','/etc/kubernetes/manifests/kube-apiserver.yaml','/etc/kubernetes/manifests/etcd.yaml','/var/tmp/minikube/kubeadm.yaml','/var/tmp/minikube/kubeadm.yaml.new')
 foreach($n in @('state-first-live.json','state-final-live.json','kubelet-journal-capture.json','containerd-journal-capture.json','cri-version-capture.json','cri-containers-capture.json')){if(-not(Test-Path -LiteralPath(Join-Path $ArtifactRoot $n))){throw "live_state_evidence_missing:$n"}}
 foreach($n in @('state-first-live.json','state-final-live.json')){$state=Read-EvidenceJson $n;if([int]$state.exit_code-ne0-or[string]::IsNullOrWhiteSpace([string]$state.stdout)){throw "state_capture_failed:$n"};foreach($path in $paths){if([string]$state.stdout-notmatch('(?m)^(?:PRESENT|MISSING)\|'+[regex]::Escape($path)+'(?:\||$)')){throw "state_path_missing:$n`:$path"}}}
 $cri=Read-EvidenceJson 'cri-containers-capture.json';if($cri.exit_code-ne0-or$cri.stdout-match '(?m)^NAME:\s+crictl'){throw 'cri_container_list_invalid'}
}
$h=Read-EvidenceJson 'host-after.json';if(-not$h.passed-or[int]$h.counts.whea_event_17-ne0-or[int]$h.counts.kernel_power_41-ne0-or[int]$h.counts.bugcheck-ne0){throw 'host_health_gate_failed'}
Write-Output "kubernetes_bootstrap_state_consistency_verification=passed id=$ExpectedDiagnosticId classification=$($a.classification)"
