[CmdletBinding()]
param(
    [Parameter(Mandatory)][string]$ArtifactRoot,
    [string]$OutputPath
)
$ErrorActionPreference='Stop';Set-StrictMode -Version Latest
function ReadJson([string]$Name){$path=Join-Path $ArtifactRoot $Name;if(-not(Test-Path -LiteralPath $path)){throw"missing_artifact:$Name"};Get-Content -LiteralPath $path -Raw|ConvertFrom-Json}
function CounterDelta([object[]]$Series,[string]$Name){$sum=0.0;foreach($s in @($Series|Where-Object{$_.metric.__name__-eq$Name})){for($i=1;$i-lt$s.values.Count;$i++){$d=[double]$s.values[$i][1]-[double]$s.values[$i-1][1];if($d-ge0){$sum+=$d}}};$sum}
function MaxRate([object[]]$Series,[string]$Name){$max=0.0;foreach($s in @($Series|Where-Object{$_.metric.__name__-eq$Name})){for($i=1;$i-lt$s.values.Count;$i++){$dt=[double]$s.values[$i][0]-[double]$s.values[$i-1][0];$d=[double]$s.values[$i][1]-[double]$s.values[$i-1][1];if($dt-gt0-and$d-ge0){$rate=$d/$dt;if($rate-gt$max){$max=$rate}}}};$max}
function GaugeMax([object[]]$Series,[string]$Name){[double]@($Series|Where-Object{$_.metric.__name__-eq$Name}|ForEach-Object{$_.values|ForEach-Object{[double]$_[1]}}|Measure-Object -Maximum).Maximum}

$hostEvidence=ReadJson 'host-after.json';if(-not$hostEvidence.passed-or-not$hostEvidence.record_id_monotonic){throw'host_gate_failed'}
$rollback=ReadJson 'rollback.json';if(-not$rollback.passed){throw'rollback_gate_failed'}
$obs=ReadJson 'pod-observations.json';if([int]$obs.duration_seconds-ne180-or[int]$obs.poll_seconds-ne5){throw'observation_contract_failed'}
$pods=@($obs.observations|ForEach-Object{$_.pods}|Where-Object{$_.name-like'recommendationservice-*'});$uids=@($pods.uid|Sort-Object -Unique);$targetUid=@($uids|Where-Object{$_})[-1];$target=@($pods|Where-Object{$_.uid-eq$targetUid});
$server=@($target|ForEach-Object{$_.containers}|Where-Object{$_.name-eq'server'});$proxy=@($target|ForEach-Object{$_.containers}|Where-Object{$_.name-eq'network-delay-proxy'});if($server.Count-lt30-or$proxy.Count-ne$server.Count){throw'pod_coverage_failed'}
$serverReady=@($server|Where-Object{$_.ready}).Count;$proxyReady=@($proxy|Where-Object{$_.ready}).Count;$serverRestartMax=[int]($server.restart_count|Measure-Object -Maximum).Maximum;$proxyRestartMax=[int]($proxy.restart_count|Measure-Object -Maximum).Maximum
$events=ReadJson 'events.json';$targetEvents=@($events.items|Where-Object{$_.involvedObject.uid-eq$targetUid});$kills=@($targetEvents|Where-Object{$_.reason-eq'Killing'-and$_.message-like'Container server failed liveness probe*'});$killOccurrences=(@($kills|ForEach-Object{[int]$_.count})|Measure-Object -Sum).Sum;if($killOccurrences-lt1-or$serverRestartMax-lt1){throw'restart_not_reproduced'}
$prom=ReadJson 'prometheus-resource-metrics.json';if($prom.status-ne'success'-or$prom.data.resultType-ne'matrix'){throw'prometheus_archive_failed'};$podName=[string]$target[-1].name;$series=@($prom.data.result|Where-Object{$_.metric.pod-eq$podName});$types=@($series.metric.__name__|Sort-Object -Unique);if($types.Count-ne13){throw'metric_type_coverage_failed'}
$times=@($series|ForEach-Object{$_.values|ForEach-Object{[double]$_[0]}});$span=($times|Measure-Object -Maximum).Maximum-($times|Measure-Object -Minimum).Minimum;if($span-lt175){throw'metric_time_coverage_failed'}
$cpu=CounterDelta $series 'container_cpu_usage_seconds_total';$periods=CounterDelta $series 'container_cpu_cfs_periods_total';$throttled=CounterDelta $series 'container_cpu_cfs_throttled_periods_total';$summary=[ordered]@{schema_version=2;verifier='network_probe_resource_diagnostic';passed=$true;classification='completed_valid_diagnostic';artifact_root=$ArtifactRoot;pod_name=$podName;pod_uid=$targetUid;observation_samples=$server.Count;server_ready_samples=$serverReady;proxy_ready_samples=$proxyReady;server_restart_max=$serverRestartMax;proxy_restart_max=$proxyRestartMax;liveness_killing_event_objects=$kills.Count;liveness_killing_occurrences=[int]$killOccurrences;metric_types=$types.Count;metric_span_seconds=$span;cpu_total_seconds=$cpu;cpu_mean_millicores=(1000*$cpu/$span);cpu_max_rate_millicores=(1000*(MaxRate $series 'container_cpu_usage_seconds_total'));throttled_seconds=(CounterDelta $series 'container_cpu_cfs_throttled_seconds_total');cfs_periods=$periods;cfs_throttled_periods=$throttled;cfs_throttled_period_fraction=if($periods){$throttled/$periods}else{$null};cpu_pressure_waiting_delta=(CounterDelta $series 'container_pressure_cpu_waiting_seconds_total');memory_working_set_max_bytes=(GaugeMax $series 'container_memory_working_set_bytes');memory_failcnt_delta=(CounterDelta $series 'container_memory_failcnt');oom_events_delta=(CounterDelta $series 'container_oom_events_total');memory_pressure_waiting_delta=(CounterDelta $series 'container_pressure_memory_waiting_seconds_total');host_new_events=$hostEvidence.counts;rollback_passed=[bool]$rollback.passed}
if($OutputPath){[IO.File]::WriteAllText($OutputPath,($summary|ConvertTo-Json -Depth 12),[Text.UTF8Encoding]::new($false))}
$summary|ConvertTo-Json -Depth 12
