[CmdletBinding()]param([Parameter(Mandatory)][string]$ArtifactRoot,[string]$OutputPath)
$ErrorActionPreference='Stop';Set-StrictMode -Version Latest
function ReadJson([string]$Name){$p=Join-Path $ArtifactRoot $Name;if(-not(Test-Path $p)){throw "missing_artifact:$Name"};Get-Content $p -Raw|ConvertFrom-Json}
function Delta([object[]]$Series,[string]$Name){$sum=0.0;foreach($s in @($Series|Where-Object{$_.metric.__name__-eq$Name})){for($i=1;$i-lt$s.values.Count;$i++){$d=[double]$s.values[$i][1]-[double]$s.values[$i-1][1];if($d-ge0){$sum+=$d}}};$sum}
function MaxGauge([object[]]$Series,[string]$Name){[double]@($Series|Where-Object{$_.metric.__name__-eq$Name}|ForEach-Object{$_.values|ForEach-Object{[double]$_[1]}}|Measure-Object -Maximum).Maximum}
$hostEvidence=ReadJson 'host-after.json';if(-not$hostEvidence.passed-or-not$hostEvidence.record_id_monotonic){throw 'host_gate_failed'};$rollback=ReadJson 'rollback.json';if(-not$rollback.passed){throw 'rollback_gate_failed'}
foreach($clean in @('proxy-clean-before.json','proxy-clean-after.json')){$p=ReadJson $clean;if(-not$p.cleanup_verified-or$p.scientific_fault_started-or@($p.after.toxics).Count-ne0-or-not$p.after.enabled){throw "proxy_clean_gate_failed:$clean"}}
$stable=ReadJson 'target-stability.json';$obs=ReadJson 'pod-observations.json';if([int]$stable.duration_seconds-ne120-or[int]$obs.duration_seconds-ne180-or[int]$obs.poll_seconds-ne5){throw 'duration_contract_failed'}
$all=@($stable.observations+$obs.observations);$active=@($all|ForEach-Object{$_.pods|Where-Object{$null-eq$_.deletion_timestamp}});$uids=@($active.uid|Sort-Object -Unique);if($uids.Count-ne1){throw 'target_uid_changed'};$uid=[string]$uids[0];$containers=@($active|ForEach-Object{$_.containers});if(@($containers|Where-Object{-not$_.ready-or$_.restart_count-ne0}).Count){throw 'lifecycle_gate_failed'}
$prom=ReadJson 'prometheus-resource-metrics.json';$pod=[string]@($active|Select-Object -Last 1)[0].name;$series=@($prom.data.result|Where-Object{$_.metric.pod-eq$pod});$types=@($series.metric.__name__|Sort-Object -Unique);if($types.Count-ne13){throw 'metric_type_coverage_failed'};$times=@($series|ForEach-Object{$_.values|ForEach-Object{[double]$_[0]}});$span=($times|Measure-Object -Maximum).Maximum-($times|Measure-Object -Minimum).Minimum;if($span-lt175){throw 'metric_time_coverage_failed'}
$periods=Delta $series 'container_cpu_cfs_periods_total';$throttled=Delta $series 'container_cpu_cfs_throttled_periods_total';$fraction=if($periods){$throttled/$periods}else{1.0};$pressure=Delta $series 'container_pressure_cpu_waiting_seconds_total';$failcnt=Delta $series 'container_memory_failcnt';$oom=Delta $series 'container_oom_events_total';$memoryPressure=Delta $series 'container_pressure_memory_waiting_seconds_total';if($fraction-ge0.50){throw 'throttled_fraction_gate_failed'};if($pressure-ge10.635359){throw 'cpu_pressure_gate_failed'};if($failcnt-ne0-or$oom-ne0-or$memoryPressure-ne0){throw 'memory_gate_failed'}
$before=ReadJson 'node-before.json';$after=ReadJson 'node-after.json';foreach($name in @('MemoryPressure','DiskPressure','PIDPressure')){if(($before.status.conditions|Where-Object{$_.type-eq$name}).status-ne'False'-or($after.status.conditions|Where-Object{$_.type-eq$name}).status-ne'False'){throw "node_pressure_gate_failed:$name"}}
$result=[ordered]@{schema_version=1;classification='valid';passed=$true;run_id='ob-network-resource-compat-002';pod=$pod;uid=$uid;stability_samples=$stable.observations.Count;measurement_samples=$obs.observations.Count;metric_types=$types.Count;metric_span_seconds=$span;cfs_periods=$periods;cfs_throttled_periods=$throttled;cfs_throttled_period_fraction=$fraction;cpu_pressure_waiting_delta=$pressure;memory_working_set_max_bytes=(MaxGauge $series 'container_memory_working_set_bytes');memory_failcnt_delta=$failcnt;oom_events_delta=$oom;memory_pressure_waiting_delta=$memoryPressure;host_new_events=$hostEvidence.counts;rollback_passed=[bool]$rollback.passed}
if($OutputPath){[IO.File]::WriteAllText($OutputPath,($result|ConvertTo-Json -Depth 10),[Text.UTF8Encoding]::new($false))};$result|ConvertTo-Json -Depth 10
